### PR TITLE
Fix react unmatching tree on NavBar offset adjustment

### LINKED ISSUE #41: Fix React unmatching prerendered layout
We use server render, which have no DOM

React throws error when mounting. It can't validate prerendered tree, then wipes everything and renders from scratch

That's not good, mobile devices will experience rare lag during page load

Error itself

```
main.js:16 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) rue-active" offset="-49" data-reactid=".
 (server) rue-active" offset="0" data-reactid=".76
```

Thrown by this thing (selected)

image

This is NavBar component: https://github.com/Lingvokot/lingvokot.github.io/blob/58121600149518824c6737d1ad3f45463b53c7a7/src/components/Navbar.js#L52-L53

Solution:  this actually looks like hack. Do we really need it?

### PR DESCRIPTION
**Pull request by ColCh**
Close #41 
See that issue for more info

### CODE REVIEW

**Comment by ColCh** [comment]
I recommend to checkout into this branch before merging and check the things that removed line was written for.

I can't notice visible difference

**Comment by keshan3262** [comment]
Well, it's a good solution. However, scrolling to link may become broken if width or height of the inner window changes, like here (both screenshots were made after cliking "Socials" link): 
screenshot_20170417_205114
screenshot_20170417_205232

**Comment by ColCh** [comment]
Ah, ya. 
It needs resize event handler. 

I will update PR later

**Comment by keshan3262** [comment]
After clicking on 'Socials' link I get this: 
screenshot_20170418_095448
Call `adjustNavBar()` in `componentDidMount` and all will be okay.

**Comment by keshan3262** [comment]
After clicking on "Socials" link I get this:
screenshot_20170418_095448
However, I don't know how to both fix it and fix this issue

**Comment by ColCh** [comment]
Solution is: trigger navbar adjustment after mount.

This is how Socials link looks like now:

image

**Pull request merged**
