### PR TITLE
Replaced CDN semantic-ui with semantic-ui-css package

### LINKED ISSUE #32: Redesign prev/next buttons in carousel
This requires some discussion on how it should look like. Any ideas?

### LINKED ISSUE #44: Bundle semantic-ui css, don't use CDN version
As https://github.com/Lingvokot/lingvokot.github.io/pull/43 , we are using semantic-ui React version, but CSS is gets included by CDN 

This is actually related to https://github.com/Lingvokot/lingvokot.github.io/issues/28

### PR DESCRIPTION
**Pull request by keshan3262**
Close #44 
Close #32

### CODE REVIEW

**Comment by ColCh** [comment]
This is probably related to #32  ?

**Comment by keshan3262** [comment]
Oh, yeah. Forgot to add to the comment

**Comment by ColCh** [comment]
It seems that something went wrong with the semantic-ui stylesheet

image

This is a version from *dist* (`npm run static`)

**Comment by keshan3262** [comment]
Oy-wey! Try building once more. I have no such problems

**Comment by ColCh** [comment]
Yup. That was my browser's cache :)

**Pull request merged**
